name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/20 * * * *'
jobs:
  get-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          ssh-key: ${{secrets.SOF_REACT_DEPLOY_KEY}}

      - run: mkdir api
      - run: touch api/.placeholder
      - run: git status
      - run: git add api
      - run: sudo apt install wget && sudo apt clean && sudo rm -rf /var/lib/apt/lists/*
      - run: wget http://sof1.megalag.org/text/server-list.txt -O ./api/serverlist.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: squash me

